@echo off
echo Developer's documentation (html)...
makeinfo --html --no-split --no-headers --css-include=body.css --output=odt2braille-dev-doc.html odt2braille-dev-doc.texi
echo Developer's documentation (pdf)...
texi2dvi --pdf odt2braille-dev-doc.texi
echo User's documentation (html)...
makeinfo --html --no-split --no-headers --css-include=body.css --output=odt2braille-user-doc.html odt2braille-user-doc.texi
echo User's documentation (pdf)...
texi2dvi --pdf odt2braille-user-doc.texi
@pause
exit