package be.docarch.odt2braille;

import be.docarch.odt2braille.setup.Configuration;

public class AutoGeneratedVolume extends Volume {

    private int startPage;

    public AutoGeneratedVolume(Configuration.SplittableVolume settings,
                               int startPage) {
        
        super(settings);
        this.startPage = Math.max(1, startPage);
    }

    public int getStartPage() { return startPage; }
}
